let dinners = [
    "spaghetti and meatballs", "stir-fry", "pork noodles", "smash burgers",
    "Paul's chili", "feijoada", "estroganofe de frango", "chicken panquecas",
    "bebimbap", "black bean mango stew", "chicken parmesan", "stroganoff",
    "grilled steaks and dogs", "roast and mashed potatoes", "lasagna",
    "Brasilian lasanha", "burger dogs", "cachorro quente", "pizza", "gnocchi",
    "chicken fried steak", "chicken noodle soup", "chicken pot pie", "shepherd's pie",
    "chili baked potato", "espetinhos", "tacos", "sweet pulled pork", "oven nachos",
    "homemade burgers and buns", "sliders", "corned beef and Irish soda bread",
    "bean dip", "tuna mac", "tuna melts", "chicken nuggets", "chicken sandwiches",
    "meatball subs", "rib-a-cue sandwiches", "curry", "twice-baked potatoes",
    "zucchini soup", "meatloaf", "white-bean chicken chili", "sausage-pepper pasta",
    "hosanna stew", "Greek lemon chicken soup", "CostCo rotisserie chicken",
    "ham and funeral potatoes", "baked ham & cheese", "Tasty fajita pasta", "fajitas",
    "classic chili", "beef stew", "manicotti", "carbonara", "chicken salad sandwiches",
    "taco salad", "chef salad", "Chicken Penne Doolittle", "macaroni & cheese-burger",
    "chili cheese fries", "enchiladas", "tetrazinni", "BLT street tacos", "buttered noodles",
    "hot dog boats", "BLTs", "breakfast for dinner", "dutch oven meat and spuds", "fettucine alfredo",
    "Chinese Sundaes", "crunch wraps", "Missionary Surprise", "Dad's ground beef stew",
    "Ramen noodles", "sweet and sour chicken on rice", "Salisbury steak", "grilled cheese and tomato soup",
    "macaroni and cheese", "Sloppy Joes", "potato soup", "chili dogs", "French dip",
    "baked chicken legs and thighs", "Kahlua pork", "garlic chicken pizza", "Mexican Haystacks",
    "gyros", "quesadillas", "sliders", "coconut shrimp", "chicken pesto paninis",
    "jambalaya", "ribs", "split-pea soup", "creamy bratwurst stew", "stuffed pasta shells",
    "mushroom pork chops on rice", "tuna salad pitas", "pesto pasta", "beef bulgogi"
];

let breakfasts = [
    "bangers and mash", "French toast", "Surpresa", "breakfast sandwiches",
    "breakfast burritos", "omelets", "breakfast chicken sandwiches",
    "breakfast dogs", "eggs benedict", "biscuits and gravy", "sausages",
    "shakshuka", "crepes", "German pancakes", "blueberry pancakes",
    "cinnamon rolls", "coffee cake", "muffins", "frittata", "quiche",
    "scrambled eggs O’Brien", "smoothies", "eggs in a hole", "deviled eggs",
    "Monte Cristo sandwiches", "Uncle Var's dutch-oven spuds", "whole wheat waffles",
    "yogurt granola parfaits", "oatmeal", "Fūl Medames", "huevos rancheros",
    "cuscuz", "breakfast BLTs", "donuts", "avocado toast", "hash browns",
    "pumpkin waffles", "breakfast casserole", "scones with honey butter",
    "a pork patty sandwich"
];

let desserts = [
    "ice cream", "milkshakes", "pudim de leite", "Romeo e Juliete", "s'mores",
    "Funfetti cake", "root beer floats", "coconut cream pie", "s'mores dip",
    "tres leches cake", "peanut butter cornflake cookies", "no-bake cookies",
    "millionaire shortbreads", "apple pie", "blueberry pie", "pineapple cream pie",
    "Rice Krispie treats", "Black Forest cake", "brownies", "ice cream sundaes",
    "Captain Crunch", "Cinnamon Toast Crunch", "strawberry shortcake",
    "pineapple upside-down cake", "toasted coconut peanut butter cookies",
    "chocolate chip cookies", "chocolate cake", "banana bread", "pumpkin pie",
    "rhubarb crunch", "pumpkin chocolate chip muffins", "banana cream pie",
    "orange rolls", "lemon bread", "Muddy Buddies", "kettle corn", "kugel",
    "Chex Crack", "ice cream sandwiches", "cheesecake", "lemon meringue pie",
    "banana splits", "marshmallow brownies", "homemade Oreos", "grasshopper pie",
    "a pazookie", "dessert pizza", "better than X cake", "parfait", "trifle",
    "turnovers", "donuts", "black cherry floats", "macarons", "macaroons",
    "divinity", "cake roll", "snickerdoodles", "snickerdoodle blondies", "chocolate crinkle cookies",
    "fruit tarts", "Jello cottage cheese salad", "cathedral window cookies",
    "popsicles", "frozen yogurt", "lemon bars", "fudge", "blondies", "candied nuts",
    "peppermint bark", "toffee", "brigadeiro", "quindins", "fruit and dip", "frozen bananas",
    "caramel corn", "frosted sugar cookies", "slush", "angel food cake",
    "buckeyes", "cobbler", "pumpkin roll", "monkey bread", "Sandy Sherbet Pie",
    "brigadeiro", "beijinhos", "gaumy popcorn", "lime frappé", "mango rice",
    "pecan pie", "eggnog", "mud pudding", "bread pudding"
];

let snacks = [
    "potato salad", "rhubarb muffins", "lemon poppy seed muffins", "cheeseball and crackers",
    "Texas caviar", "ramen salad", "Caesar salad", "jalapeño poppers", "rattlesnake bites",
    "a cactus blossom", "oven-baked potato wedges", "seven-layer dip", "pizza bites", "broccoli salad", "grilled corn on the cob",
    "BYU-I spinach salad", "pasta salad", "coleslaw", "baked beans", "pão de queijo", "grape Jello salad",
    "Dot's pretzels", "soft pretzels", "spinach dip", "artichoke dip", "chips and dip", "crackers and cheese",
    "twice-baked potatoes", "mashed potatoes", "cheese sticks", "breadsticks", "fondue", "cheddar biscuits",
    "roasted chickpeas", "hummus", "chips and salsa", "Li'l Smokies", "pigs in a blanket", "onion dip",
    "taquitos", "Chex party mix", "wantons", "scones", "strawberry lemonade", "chicken nuggets", "buffalo chicken dip",
    "buffalo wings", "cucumber sandwiches", "meatballs", "tortilla roll-ups", "chips and guacamole",
    "macaroni and cheese", "green bean casserole", "sweet potato casserole", "deviled eggs", "risotto",
    "roasted vegetables", "roasted potatoes", "asparagus", "tater tots", "fries", "garlic bread", "hush puppies",
    "fondant potatoes", "fried rice", "Spanish rice", "au gratin potatoes", "rolls", "corn bread", "onion rings",
    "sunshine carrots", "Hungarian cucumber salad", "mini corn dogs", "popcorn"
];
